# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  aspnet:
    build:
      context: "C:\\Users\\Admin\\OneDrive - WK sp. z o.o\\Pulpit\\test\\Hackaton\\\
        frontend\\ClientFrontend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/ClientFrontend.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/ClientFrontend.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\Admin\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\Admin\\.nuget\\packages"
    image: "aspnet:dev"
    ports: []
    volumes:
    - "C:\\Users\\Admin\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\Admin\\OneDrive - WK sp. z o.o\\Pulpit\\test\\Hackaton\\frontend\\\
      ClientFrontend:/app:rw"
    - "C:\\Users\\Admin\\OneDrive - WK sp. z o.o\\Pulpit\\test\\Hackaton\\frontend:/src:rw"
    working_dir: "/app"
