# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  aspnet:
    build:
      context: "C:\\Users\\Filip Kwiek\\Desktop\\Hakaton\\frontend\\ClientFrontend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/ClientFrontend.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/ClientFrontend.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\Filip Kwiek\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\Filip Kwiek\\.nuget\\packages"
    image: "aspnet:dev"
    ports: []
    volumes:
    - "C:\\Users\\Filip Kwiek\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\Filip Kwiek\\Desktop\\Hakaton\\frontend\\ClientFrontend:/app:rw"
    - "C:\\Users\\Filip Kwiek\\Desktop\\Hakaton\\frontend:/src:rw"
    working_dir: "/app"
